name: Product Monitor
on:
  schedule:
    - cron: '*/25 * * * *'  # 每25分钟运行
  workflow_dispatch:
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@noreply.github.com"
          git add last_product.txt
          git commit -m "Update product" || echo "No changes"
          git push
